{% set version = "3.1.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ecp
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ecp_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ecp/ecp_{{ version }}.tar.gz
  sha256: a80ab10bafe30cc96287b9220e44c4b4eda40f5dd0546e4d2a2e1baab514c058

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp

test:
  commands:
    - $R -e "library('ecp')"           # [not win]
    - "\"%R%\" -e \"library('ecp')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=ecp
  license: GPL (>= 2)
  summary: Implements various procedures for finding  multiple change-points. Two methods make use of dynamic  programming and pruning, with no distributional  assumptions other than the existence of certain absolute  moments in one method. Hierarchical and exact search methods  are included. All methods return the set of
    estimated change- points as well as other summary information.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: ecp
# Type: Package
# Title: Non-Parametric Multiple Change-Point Analysis of Multivariate Data
# Version: 3.1.1
# Date: 2019-03-17
# Author: Nicholas A. James, Wenyu Zhang and David S. Matteson
# Maintainer: Wenyu Zhang <wz258@cornell.edu>
# Description: Implements various procedures for finding  multiple change-points. Two methods make use of dynamic  programming and pruning, with no distributional  assumptions other than the existence of certain absolute  moments in one method. Hierarchical and exact search methods  are included. All methods return the set of estimated change- points as well as other summary information.
# License: GPL (>= 2)
# Depends: R (>= 3.00), Rcpp
# Suggests: mvtnorm, MASS, combinat, R.rsp
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Repository: CRAN
# VignetteBuilder: R.rsp
# Packaged: 2019-03-18 03:18:25 UTC; wenyu
# Date/Publication: 2019-03-18 05:30:07 UTC
