travis:
  secure:
    BINSTAR_TOKEN: WIXWJVTBJgT4+5jnRm4ISUJbOhZ+2cRjd1gdFdZGyE983Wor0iigu95SU6m3afcWoge3p6ucnmhwDb+W6Y8E1NXPOsagIeV99BqNJFzptydEAgbJaduxlUpXaK8EKMqtNhuTDGOYqlkJGMkjClxV4v/iQTzyJ5887b4QmiLvfWieqtbJKT+tkEpuz6o+Fn9a21TOeEh0yaWJFDK66jzXACjgFDBgHpomCs8Kg+rRi8zNhKrvd0aUwyC+2nDcoO2wmfe1NxRvykqF9I85arCZ9GKyWr2TolAvEF5AnnC1McUo7KOJKPeklszkWEwbjjUvji5dyKJAYlg+NT5XMJqGhgL9mCHfLwzwsCDGFSFT915lGJRM/V3vcTWk1zKEZxuuYMB/UATc+JOyzEOgMMan3SLfNsjKwNVIQyOgrDRl088rI3AQ70awUXFZSsOmjdM2gDxkKS18OPiVeexrf6hwmjouBM9tvnVl8KZMXTZB1dk7y92ydyYdMKehMBs/jtRPdU7xWZnNwAKfJpT+SDEqXwNqZfohNV676tS62d2yTUXPtyhxMsrUw0uz78sMsBwQXSHOTRv6Q93KQeOJQHyqhqNV/T237N/Nt1wrgs8lHCTYt5N0b+vXPsjuMd3rqIs4o3dD10ssmLtXXR1MjLVExq2dm5/liu3yHjm6ohOa5Qo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
