appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: iZmb/EM70nQ194MJTipXGP56BjL1c+twSWKRp7W/mH1qd7700ANHI/cTN1bjZIhxuqssMWQd957BjkSEV+d3P/wLnEOum7sDz4qhCBsgL4xe+HIwxA8Cq2dRPAIHsm9nowyk/gf0xYOAVzY34uQ0ZU2oD2ycrKcnbDL+UoOl9Y2vISNtF+tCkapNrfQsSjzsuAms7T49PzFIaKrG5Lh9wMXAcTLNLp6f910RSV2mfoxlaPweQ1GeEMjPi9UUdEbjmLUisJlUM4P9iQIOxD1uAdUVND8gryJygspCg0tr2U8ZT09oCzw21JTSFfXYxnTvQvSomhTNoRrLSWcyiLxeIOkAREMGB73H4sEfNAhn5k4BMQpAMdcuPQdDT9dumtkNSJLmnBz7prAQ1DmZFnc5teHZK8JIr6u1pJOFWJe2jeF33ZG/R5eKsA923WjI3NBECkTz7u3vfwCv046/BaynM4rjFgml7lKxPNula/ONiPwqOfaPxpKVEQWpPpe6LGrZadn7wmLG80C7U2ER5Zg8E0WYTNbBOAOkWeO/DAP7YzGSy734pUlcwbl8s1hhe0CFAs0WvISVxPk+xI8nRsIdV+aGnUAGks4T3nBpYmm3ZI74MaQCDsotmgoTXXk4aNyCCjLKdKnQjjc1GQj4OTqEUVpbWvgg/tj4bvTsqCYSpIM=}
